version: '3'

services:
    node:
        image: node:12-alpine
        tty: true
        volumes:
            - ./:/var/www
        working_dir: /var/www
        entrypoint: yarn serve
        ports:
            - 8081:8080
